QUESTION_UX_MAP = {
    "Question : lombalgie commune / lombo-sacre / deviation ?": "C'est une lombalgie commune, un problème lombo-sacré, ou une déviation ?",
    "Question : lombalgie commune ou autre atteinte rachis ?": "C'est une lombalgie commune ou un autre problème du rachis ?",
    "Question : cervicalgie / trauma recent / deviation ?": "C'est une cervicalgie simple, un traumatisme récent, ou une déviation ?",
    "Question : dorsal ou deviation ?": "C'est le rachis dorsal classique ou une déviation (scoliose, cyphose) ?",
    "Question : plusieurs segments ou deviation ?": "Ça concerne plusieurs segments du rachis, ou c'est une déviation ?",
    "Question : cervical / dorsal / lombaire / plusieurs segments ?": "Quel segment : cervical, dorsal, lombaire, ou plusieurs ?",
    "Question : moins de 18 ans ?": "Le patient a moins de 18 ans ?",
    "Question : trauma recent ou autre atteinte rachis ?": "C'est un traumatisme récent ou un autre problème du rachis ?",
    "Question : trauma recent ?": "C'est un traumatisme récent ?",
    "Question : chirurgie du genou ou non ?": "Le genou a été opéré ?",
    "Question : prothese / lca / meniscectomie / autre ?": "Quel type d'opération : prothèse, LCA, méniscectomie, ou autre ?",
    "Question : chirurgie de hanche ou non ?": "La hanche a été opérée ?",
    "Question : prothese de hanche ou autre ?": "C'est une prothèse de hanche ou une autre chirurgie ?",
    "Question : operee ? entorse ? referentiel ?": "C'est opéré, une entorse, ou autre chose ?",
    "Question : operes ou non ?": "C'est opéré ou non opéré ?",
    "Question : operes ou non ? confirmer bilateral.": "Les deux côtés sont opérés ou non ?",
    "Question : genou / cheville / hanche ?": "C'est le genou, la cheville, ou la hanche ?",
    "Question : quel contexte du membre inferieur ?": "C'est le genou, la cheville, ou la hanche ?",
    "Question : operee ? coiffe ? fracture ? referentiel ?": "C'est opéré, la coiffe, une fracture, ou autre chose ?",
    "Question : coiffe operee ou non ?": "La coiffe a été opérée ?",
    "Question : operee ou non ?": "C'est opéré ou non ?",
    "Question : canal carpien opere ou non ?": "Le canal carpien a été opéré ?",
    "Question : epaule / coude / poignet ?": "C'est l'épaule, le coude, ou le poignet/main ?",
    "Question : quel type neurologique ?": "Quel type : hémiplégie, paraplégie, myopathie, ou autre ?",
    "Question : neuro peripherique ou rachis ?": "C'est plutôt nerveux (neuro) ou un problème de rachis ?",
    "Question : Un membre ou plusieurs ?": "Un seul membre ou plusieurs ?",
    "Question : encéphalopathie infantile ou paralysie cérébrale / polyhandicap ?": "Encéphalopathie infantile ou paralysie cérébrale / polyhandicap ?",
    "Question : Hémiplégie, paraplégie/tétraplégie, myopathie ou autre ?": "Hémiplégie, paraplégie/tétraplégie, myopathie, ou autre ?",
    "Question : Quelle atteinte neurologique ?": "Quel type d'atteinte neurologique ?",
    "Question : Quel type d'atteinte respiratoire ?": "Quel type : bronchiolite, BPCO, mucoviscidose, pré/post-op, ou autre ?",
    "Question : Individuel ou groupe ?": "Séance individuelle ou en groupe ?",
    "Question : Un membre ou deux ?": "Un membre ou deux ?",
    "Question : Un ou deux membres + localisation ?": "Un ou deux membres touchés ?",
    "Question : Lymphœdème simple ou post-cancer du sein ?": "Lymphœdème simple ou après cancer du sein ?",
    "Question : Quel type d'atteinte vasculaire ?": "Bandage, lymphœdème, artériopathie, ou insuffisance veineuse ?",
    "Question : Pré/post-op ou post-partum ?": "C'est pré/post-opératoire ou post-partum ?",
    "Question : Abdominal ou périnéal ?": "Abdominal ou périnéal ?",
    "Question : Membre supérieur, inférieur ou plusieurs ?": "Membre supérieur, inférieur, ou plusieurs ?",
    "Question : Un membre ou plusieurs / tronc ?": "Un seul membre ou plusieurs / tronc ?",
    "Question : Chirurgie sur un des territoires ?": "Un des territoires a été opéré ?",
    "Question : Atteinte localisée ou plusieurs membres ?": "Atteinte localisée ou plusieurs membres ?",
    "Question : Maxillo, vestibulaire ou déglutition ?": "Mâchoire, vertiges/équilibre, ou déglutition ?",
    "Question : quel diagnostic precis ?": "Pouvez-vous préciser le diagnostic ?",
    "Question : soins palliatifs - cotation journaliere forfaitaire confirmee ?": "Confirmer soins palliatifs ?",
    "Question : deambulation sujet age confirmee ?": "Rééducation de la marche chez la personne âgée ?",
    "Cotation impossible sans précision clinique complémentaire.": "Je n'ai pas assez d'infos pour coter. Pouvez-vous préciser ?",
}


def humaniser_question(texte: str) -> str:
    return QUESTION_UX_MAP.get(texte, texte)
